name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Navigate to project directory
            cd /home/opc/personal/jointventure || exit

            # Pull latest changes
            git pull origin main

            # Create .env file (Hardfix for Prod)
            echo "PORT=5000" > server/.env
            echo "MONGO_URI=mongodb+srv://jointventure:0P2cY0he8CZ6p3WP@safe360demo.l1ablip.mongodb.net/jointventure?appName=Safe360Demo" >> server/.env
            echo "JWT_SECRET=c1ed81fde4f14173b534f3c022559362d7732e188e458a4f4c4795294df9b962" >> server/.env

            # Install server dependencies
            cd server && npm install
            
            # Seed Database (Ensure Admin is updated)
            node seeder.js

            # Install client dependencies and build
            cd ../client && npm install && npm run build
            
            # Go back to root
            cd ..

            # Reload PM2
            pm2 reload all
            pm2 save
